baseURL: "https://aome510.github.io/"
title: "AOWeb"
theme: "PaperMod"
enableEmoji: true

params:
  disableSpecial1stPost: true
  ShowBreadCrumbs: true

  assets:
    favicon: "/favicon.ico"

  profileMode:
    enabled: true
    title: "Thang Pham"
    subtitle: "Keep learning... It's never enough.\n\nðŸ¤– Building next-generation self-driving trucks at [Waabi AI](https://waabi.ai)"
    imageUrl: "4leaf.png"

    buttons:
      - name: "About"
        url: "/about"
      - name: "Resume"
        url: "/resume.pdf"
      - name: "Posts"
        url: "/posts"

  socialIcons:
    - name: "github"
      url: "https://github.com/aome510"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/aome510/"
    - name: "email"
      url: "mailto:phamducthang1234@gmail.com"
